### ISSUE TITLE
The blockprocessor experiences errors when run against infura

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#227]
There are two errors that you'll see if you run PISA for long enough.

1. Unknown block
2019-07-23T12:34:33.787Z error: There was an error fetching blocks: unknown block
2019-07-23T12:34:33.788Z error: Error: unknown block
    at getResult (/usr/pisa/node_modules/ethers/providers/json-rpc-provider.js:40:21)
    at exports.XMLHttpRequest.request.onreadystatechange (/usr/pisa/node_modules/ethers/utils/web.js:111:30)
    at exports.XMLHttpRequest.dispatchEvent (/usr/pisa/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/pisa/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/pisa/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

2. 'Hash' of null
2019-07-23T12:39:34.409Z error: There was an error fetching blocks: Cannot read property 'hash' of null
2019-07-23T12:39:34.409Z error: TypeError: Cannot read property 'hash' of null
    at Object.<anonymous> (/usr/pisa/build/src/blockMonitor/blockProcessor.js:26:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/pisa/build/src/blockMonitor/blockProcessor.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by bigspider** [comment]
The problem is that getBlock can return `null` (which is not well documented); when I wrote the BlockProcessor, I was assuming that it would never return `null` for a blockNumber/blockHash whose existence is already verified. It might be false for Infura, perhaps because different API requests might be served by different nodes (that could be lagging behind).
Moreover, it seems that getBlock is sometimes throwing an error rather than returning null (might need to verify this more.

One way to resolve the issue could be as follow:
1) Modify the BlockCache to make it possible to add blocks immediately, rather than adding the parent first, but still keep track of the blocks that are _"complete"_ (where a block is _complete_ iff its depth is `maxDepth` or its parent is _complete_).
2) Modify the BlockProcessor to always check if a block is already in the BlockCache before downloading it, so that failures can easily be recovered with a later attempt without duplicate work (that is, each block is requested only once from the provider).

NEW_BLOCK and NEW_HEAD events should still only be generated on _complete_ blocks, so this would not change the semantics of the class.
