### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#275]
{"name":"pisa","hostname":"832fe7464a1c","pid":1,"requestId":"835d9295-d41a-4fee-9207-2c42b7250968","level":50,"err":{"message":"invalid address (arg=\"\", coderType=\"address\", value=\"0x1234\", version=4.0.27)","name":"Error","stack":"Error: invalid address (arg=\"\", coderType=\"address\", value=\"0x1234\", version=4.0.27)\n    at Object.throwError (/usr/pisa/node_modules/ethers/errors.js:76:17)\n    at CoderAddress.encode (/usr/pisa/node_modules/ethers/utils/abi-coder.js:507:20)\n    at /usr/pisa/node_modules/ethers/utils/abi-coder.js:645:59\n    at Array.forEach (<anonymous>)\n    at pack (/usr/pisa/node_modules/ethers/utils/abi-coder.js:644:12)\n    at CoderTuple.encode (/usr/pisa/node_modules/ethers/utils/abi-coder.js:804:16)\n    at AbiCoder.encode (/usr/pisa/node_modules/ethers/utils/abi-coder.js:941:77)\n    at Appointment.encode (/usr/pisa/build/src/dataEntities/appointment.js:254:68)\n    at Appointment.<anonymous> (/usr/pisa/build/src/dataEntities/appointment.js:150:79)\n    at Generator.next (<anonymous>)","code":"INVALID_ARGUMENT"},"msg":"invalid address (arg=\"\", coderType=\"address\", value=\"0x1234\", version=4.0.27)","time":"2019-08-14T10:38:34.531Z","v":0}
{"name":"pisa","hostname":"832fe7464a1c","pid":1,"requestId":"835d9295-d41a-4fee-9207-2c42b7250968","level":50,"req":{"method":"POST","url":"/appointment","headers":

Request:
{"host":"18.219.31.158:5487","user-agent":"curl/7.58.0","accept":"*/*","content-type":"application/json","content-length":"690"},"remoteAddress":"124.158.147.206","remotePort":49044},"res":{"statusCode":500,"header":"HTTP/1.1 500 Internal Server Error\r\nX-Powered-By: Express\r\nX-RateLimit-Limit: 5\r\nX-RateLimit-Remaining: 4\r\nDate: Wed, 14 Aug 2019 10:38:34 GMT\r\nX-RateLimit-Reset: 1565779151\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: 36\r\nETag: W/\"24-fQ2146iTRpnz86iOZQ2FbrvkyMA\"\r\nConnection: keep-alive\r\n\r\n"},"duration":6130.181,"requestBody":{"challengePeriod":50,"contractAddress":"0x6dDD0Ac7Efb50a519265806EeEE40fc60CA6c633","customerAddress":"0x1234","customerSig":"0x2345","data":"0x3456","eventABI":"event Test(address indexed)","eventArgs":"0x0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000bbf5029fd710d227630c8b7d338051b8e76d50b300000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000","gasLimit":"1000000","id":123456,"jobId":1,"mode":1,"paymentHash":"0xfc1624bdc50da30f2ea37b7debabeac1f6166db013c5880dcf63907b04199138","preCondition":"0","postCondition":"0","refund":"100","startBlock":12345,"endBlock":20000},"msg":"Error response.","time":"2019-08-14T10:38:34.532Z","v":0}

**Comment by yahgwai** [comment]
Another different one:

[
{
"name": "pisa",
"hostname": "a68945812baf",
"pid": 1,
"requestId": "2d928c81-328b-4068-9757-8030fda764d9",
"level": 50,
"err": {
"message": "invalid bytes value (arg="", coderType="bytes", value="0", version=4.0.27)",
"name": "Error",
"stack": "Error: invalid bytes value (arg="", coderType="bytes", value="0", version=4.0.27)\n at Object.throwError (/usr/pisa/node_modules/ethers/errors.js:76:17)\n at CoderDynamicBytes.encode (/usr/pisa/node_modules/ethers/utils/abi-coder.js:580:20)\n at /usr/pisa/node_modules/ethers/utils/abi-coder.js:645:59\n at Array.forEach ()\n at pack (/usr/pisa/node_modules/ethers/utils/abi-coder.js:644:12)\n at CoderTuple.encode (/usr/pisa/node_modules/ethers/utils/abi-coder.js:804:16)\n at AbiCoder.encode (/usr/pisa/node_modules/ethers/utils/abi-coder.js:941:77)\n at Appointment.encode (/usr/pisa/build/src/dataEntities/appointment.js:264:69)\n at Appointment. (/usr/pisa/build/src/dataEntities/appointment.js:154:79)\n at Generator.next ()",
"code": "INVALID_ARGUMENT"
},
"msg": "invalid bytes value (arg="", coderType="bytes", value="0", version=4.0.27)",
"time": "2019-08-14T11:40:10.387Z",
"v": 0
},
{
"name": "pisa",
"hostname": "a68945812baf",
"pid": 1,
"requestId": "2d928c81-328b-4068-9757-8030fda764d9",
"level": 50,
"req": {
"method": "POST",
"url": "/appointment",
"headers": {
"host": "18.219.31.158:5487",
"accept": "application/json",
"content-type": "application/json",
"content-length": "651",
"connection": "close"
},
"remoteAddress": "86.15.2.167",
"remotePort": 55062
},
"res": {
"statusCode": 500,
"header": "HTTP/1.1 500 Internal Server Error\r\nX-Powered-By: Express\r\nX-RateLimit-Limit: 5\r\nX-RateLimit-Remaining: 4\r\nDate: Wed, 14 Aug 2019 11:40:10 GMT\r\nX-RateLimit-Reset: 1565782848\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: 36\r\nETag: W/"24-fQ2146iTRpnz86iOZQ2FbrvkyMA"\r\nConnection: close\r\n\r\n"
},
"duration": 6931.753,
"requestBody": {
"challengePeriod": 10,
"contractAddress": "0xD2d2F63C15C2CC34241484FCF46A57e8F6B779fF",
"customerAddress": "0x3bBcbc6B6b93A59F0d5E6ec44782FB7FaA1Ac2F3",
"customerSig": "0x9e64b53b935602cd0657343C69Fe200fb3cD05c8",
"data": "0x28fb",
"endBlock": 6052995,
"eventABI": "event Distress(string indexed message)",
"eventArgs": "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000",
"gasLimit": "1000000",
"id": 333,
"jobId": 3,
"mode": 1,
"paymentHash": "0xfc1624bdc50da30f2ea37b7debabeac1f6166db013c5880dcf63907b04199138",
"preCondition": "0",
"postCondition": "0",
"refund": "10000000",
"startBlock": 6051077
},
"msg": "Error response.",
"time": "2019-08-14T11:40:10.389Z",
"v": 0
}
]
